version: '3.8'

services:
  # Zombie UI Application
  zombie-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zombie-ui
    env_file:
      - .env.dev.zombie-ui  # Use development environment file
    ports:
      - "18080:8080"  # Publish UI on port 18080
    volumes:
      # Mount source code for development (remove in production)
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - replication-monitor

  # Replication Monitor Service
  replication-monitor:
    image: ghcr.io/hodlontoyourbutts/replication-monitor:latest
    container_name: replication-monitor
    env_file:
      - .env.dev.couchdb  # Use CouchDB environment file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  default:
    name: development
